# This rule is not used by the project kubernetes-sakuracloud-secrets itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the secrets.t-inagaki.net.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-sakuracloud-secrets
    app.kubernetes.io/managed-by: kustomize
  name: sakuracloudsecret-editor-role
rules:
- apiGroups:
  - secrets.t-inagaki.net
  resources:
  - sakuracloudsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.t-inagaki.net
  resources:
  - sakuracloudsecrets/status
  verbs:
  - get
