apiVersion: secrets.t-inagaki.net/v1beta1
kind: SakuraCloudSecret
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-sakuracloud-secrets
    app.kubernetes.io/managed-by: kustomize
  name: sakuracloudsecret-sample
spec:
  vaultResourceID: 0 # vault resource id
  apiKey:
    secretName: api-key
  
  name: test-yaml # secret item name
  format: yaml # or json, default json

  destinationSecretName: dest-secret
